docs: :memo: updated documentation

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,7 +5,7 @@ if [ "$GITHUB_ACTIONS" = "true" ] || git log -1 --pretty=%B | grep -q "\[skip ci
   exit 0
 fi
 
-FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(ts|mts|tsx|js|mjs|json|css|scss|sass)$' || true)
+FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(ts|mts|tsx|js|mjs|json|css|scss|sass)$' | grep -v 'content/docs' || true)
 [ -z "$FILES" ] && exit 0
 
 # Block manual version bumps in package.json files
@@ -21,6 +21,6 @@ if git diff --cached -S '"version":' -- "**/package.json" \
 fi
 
 # Run Biome (Lint/Format)
-pnpm biome check --write --no-errors-on-unmatched $FILES
+echo "$FILES" | xargs -n 50 pnpm biome check --write --no-errors-on-unmatched
 
 git add $FILES
